[versions]
hamkrest = "1.8.0.1"
junit-jupiter = "5.9.3"
kotlin = "1.9.0"
kotlinter = "3.15.0"

[libraries]
hamkrest = { module = "com.natpryce:hamkrest", version.ref = "hamkrest" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
